#---------------------------------#
#      General Configuration      #
#---------------------------------#

# Build version format
version: "#{build}"

# Git clone depth
clone_depth: 50


#---------------------------------#
#    Environment Configuration    #
#---------------------------------#

# Operating system
# os: Windows Server 2012 R2

# Scripts called before repo cloning
# init:
#   - git config --global core.autocrlf input

# Build matrix configuration
environment:
  matrix:
    - PLATFORM: x64
      OS: win64
      TARGET: x86_amd64

# Environment configuration
install:
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %TARGET%


#---------------------------------#
#       Build Configuration       #
#---------------------------------#

# Scripts called before build
before_build:
  - if defined APPVEYOR_REPO_TAG_NAME
      (set ARTIFACT=unrealarena-%OS%.pre.zip)
    else
      (set ARTIFACT=artifacts.zip)

# Build configuration
build_script:
  - dir /s "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt"


#---------------------------------#
#       Tests Configuration       #
#---------------------------------#

# Disable automatic tests
test: off
