language: cpp

compiler: gcc

sudo: required

os:
  - linux
  - osx

before_install:
  - ./.travis.sh "before_install"

install:
  - ./.travis.sh "install"

before_script:
  - ./.travis.sh "before_script"

script:
  - ./.travis.sh "script"

before_deploy:
  - ./.travis.sh "before_deploy"
